[project]
name = "juniors-2026-q3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "category-encoders>=2.10.0",
    "fastapi>=0.141.1",
    "ipykernel>=7.3.0",
    "lightgbm>=4.7.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "tabulate>=0.10.0",
    "uvicorn>=0.52.4",
    "xgboost>=3.4.1",
]

[project.scripts]
juniors-2026-q3 = "juniors_2026_q3:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
